---
- name: add the jenkins apt repository
  become: yes
  apt_key:
   url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
   state: present

- name: Download jenkins repository
  apt_repository:
   repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
   state: present
  become: yes

- name: Install Jenkins
  apt:
   name: jenkins
   state: present
   update_cache: yes
  become: yes

- name: Run Jenkins
  service:
   name: jenkins
   state: started

- name: Get the default password of Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Print Jenkins default password
  debug:
   var: result.stdout